micronaut:
  application:
    name: media-service
  server:
    port: 10091
app:
  media:
    service:
      distribution-domain: d7kotxxxxx.cloudfront.net
      default-expiry: 600
      key-pair-id: KYIPxxxxxxx
      private-key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAsSrccdrqF5fUJwA8/Y7KQmr3WFZjEokkE4g4AeBXWwarRjSd
        jO04daxXoWHtbd+VFuL3GBSn0I1tzksmHUFY0gk2PngGN5AtZDeKeGvAQext7DLF
        lr7H1XOsu2gjo6DA1hGVU39dP+i/X1hxSS4uX86/9Z240MFdT/1g7OxQYwVgrl9y
        voUXBIrsCXXRbFOS7Mt2BQ4PmPDZeJGl9ohPo4ewa9sIuwZhbIc9YxARFPgY9OnR
        +y6ri36OFVGiEr2Dkr6C+W9EVmd1wtiltmKKK7FLXFhBD1F2biMxYhwpcqFyuU8Y
        uhHUF7Dx227XgyBvVvtOql0pTWDzJsK5wFvSSQIDAQABAoIBAGJI2dSb0oPWKc6d
        Fji/7zrbZm5uNjYBOK9RQWjhEPUhhQDEjaaxr0Gwo0iXMAVlJKt2rAeC5foPi5wH
        GpTePK0AiUQsh55pcJUJLttRQ24PAIgpPm47Vlb2/htVUXgj5Pac+I9Ct/ONZiU5
        xlcHtJhX9SwIHJBKxT5r3UpyasITO1zCIxY7MDKW3zP7uKxhomNx0ACWa7ZUWMqe
        Y18IboMpnXKwtYibsWpAfrgU1yoQ2yUYgIewLPgEBp39+kfBbauUn+QjeHywZboJ
        tOYgwYM/nWtMsTtiFUfVYdCph+IJW6oBlu1Tu0ytk0X4L/Cik3dcREdLRj50wCGg
        s3VPqQECgYEA6YMpc4CiV+08RitxTPHzhc52rklojW07IB2xnIRYlskO8lEvRdKA
        IGY7tuvqEAnN21bE2CWeDylSn2fxNCX88Z8X2XGxsW6AJt++kxdDXnChELkJ2Www
        NRT085MbMVUh7pn9HOktb0qxx/dddA9RZcmc+yDWpHlbeOPQH35tBykCgYEAwjqd
        HiSydhpHNO0Si9B3geP+IlD5oOv6kNqPf64qXB2RMVNb9f2XIb2UjsNWmCEOZBPc
        9dVc3ewjenQkE517xhXbAse6qx6mfX2FboEkdE4iQdBHNkGT5ZRzEo2+IvNOFqC3
        Vh0v2AAW1Gmzg8QeNXSAIlJcMms9dW20GoAZdiECgYAQlvDq88iU1pXhplR2Uvoq
        F3D3EOAMrCX3MiTcKcrha4dUT9A79aiEpL65UClg2lF1s8RoVsPT7+uex5OrUMeX
        ouXe3OTy5hbUrDCt4ok2vGm09nBssfL60nJUm67i4ll2yhnhY++GaJgYzMom5K+z
        u48biEm3haep/wVaN3EngQKBgQCbCN5RKUmqK9+ax4F+SLCb5bj8+1XGtZYT+eGB
        MSxuyssSbE+DUyBHtmPWcOW2GOy7xX8iW2T9X3gSTpJddd9OhjODTJob7SNIF+Fi
        C4Nlsth1YCL3k/DR2GTh8nJKw5sZRMAS5MlDyQ5wDs9T5j+Wu59rxgIB3Mf5689P
        N+EbAQKBgA6RwMXjnLxjMm+bB2WtXB2Mz639sYSCqeWMsm1aY+cR5vE0SSXiMZJ0
        vnWfJGEaRIjNb3RPPpGikYi9nHVuSXU4X/px6DWhvfqoS7kagcZzxXNU+Tp/1tlA
        2NMnK6Rcs4YpXghO2Ir+ivnKW/nskaXOdJt/YaoGKYydZNp3oyxZ
        -----END RSA PRIVATE KEY-----

